# Generated by Django 5.0.1 on 2024-04-29 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Car Category')),
            ],
        ),
        migrations.RemoveField(
            model_name='car',
            name='img',
        ),
        migrations.RemoveField(
            model_name='car',
            name='price',
        ),
        migrations.AlterField(
            model_name='car',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Car model'),
        ),
        migrations.AddField(
            model_name='car',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat_car', to='main.category'),
        ),
    ]
